name: hyp3-fire-tracking
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.10,<3.13
  - pip
  # For packaging, and testing
  - setuptools_scm
  - pytest
  - pytest-console-scripts
  - pytest-cov
  # For running
  - gdal
  - geopandas
  - hydra-core
  - hyp3lib>=3,<4
  - matplotlib
  - netCDF4
  - numpy
  - omegaconf
  - pandas
  - plotly
  - pyarrow
  - pyproj
  - pyresample
  - rasterio
  - scikit-learn
  - shapely
  - tqdm
  - xarray
  # TODO: insert conda-forge dependencies as list here
  - pip:
      - -r requirements-static.txt
